sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - mysql
  - docker

env:
  global:
    - MYSQL_PWD=mysqlPWD

before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD("$MYSQL_PWD") WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root --password="$MYSQL_PWD" < sqlscript/all2.sql
  - sudo service mysql restart

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

before_script:
  - docker build --tag mybookstore .
  - docker run mybookstore

script: 
  - docker images
  - mvn test

  