language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x mvnw
  - sudo mysql -u root -e 'CREATE DATABASE bookstore;'

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

services:
  - mysql

script: 
  - mvn test