language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x mvnw
  - mysql -u root --password="" < sqlscript/all2.sql
  - mysql -u root --password="" < sqlscript/init.sql
  - sudo service mysql restart
  - sudo mysql -u root -e 'CREATE DATABASE bookstore;'

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

services:
  - mysql

script: 
  - mvn test