language: java

jdk:
  - oraclejdk8

before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('fangjj1998') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -u root --password="" < sqlscript/all2.sql
  - mysql -u root --password="" < sqlscript/init.sql
  - sudo service mysql restart

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

services:
  - mysql

script: 
  - mvn test