language: java

jdk:
  - oraclejdk8

before_install:
  - mysql -e 'CREATE DATABASE bookstore;'

install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true

services:
  - mysql
script: 
  - mvn test